//! TLS support for the RPC server.
//!
//! The daemon's RPC listener runs plain HTTP on a random loopback
//! port.  When `[rpc] tls = true` is set in the config, a second
//! `tokio` task binds on the user-facing address, terminates TLS,
//! and forwards the plaintext bytes to the loopback listener.  That
//! proxy also owns the optional `allow_ip` filter so the two knobs
//! compose naturally.
//!
//! Cert lifecycle:
//!
//! - `tls_cert_path` + `tls_key_path` given in config → load them
//!   verbatim.  Use this for CA-signed certs in production.
//! - Paths empty → load `<data_dir>/rpc.cert` + `<data_dir>/rpc.key`.
//!   Both files missing → generate a self-signed ECDSA P-256 pair
//!   valid for 10 years (CN = BitAiir RPC, SANs = localhost +
//!   127.0.0.1 + ::1) and write them before returning.
//!
//! On startup the caller logs the chosen source so the operator can
//! see which cert is in use.

use rcgen::{CertificateParams, DistinguishedName, DnType, KeyPair, SanType};
use rustls::ServerConfig;
use rustls::pki_types::{CertificateDer, PrivateKeyDer};
use std::io::Cursor;
use std::net::IpAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

const DEFAULT_CERT_FILENAME: &str = "rpc.cert";
const DEFAULT_KEY_FILENAME: &str = "rpc.key";
const SELF_SIGNED_VALIDITY_YEARS: i32 = 10;

/// Source of the TLS material — reported back to the caller so the
/// daemon can print a useful log line ("generated", "loaded
/// auto-generated", "loaded user-provided").
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CertSource {
    /// User pointed the config at explicit paths.
    UserProvided,
    /// Found pre-existing `<data_dir>/rpc.cert` + `rpc.key`.
    AutoLoaded,
    /// No cert found, a fresh self-signed pair was just written.
    AutoGenerated,
}

/// Load the configured cert+key, falling back to auto-generation
/// when nothing is provided.  Returns the rustls config ready to be
/// wrapped in a `TlsAcceptor`, plus where the material came from
/// and the resolved cert path (for logging).
pub fn load_or_generate(
    data_dir: &Path,
    cert_path_cfg: Option<&str>,
    key_path_cfg: Option<&str>,
) -> Result<(Arc<ServerConfig>, CertSource, PathBuf), String> {
    let (cert_path, key_path, user_provided) = match (cert_path_cfg, key_path_cfg) {
        (Some(c), Some(k)) => (PathBuf::from(c), PathBuf::from(k), true),
        (None, None) => (
            data_dir.join(DEFAULT_CERT_FILENAME),
            data_dir.join(DEFAULT_KEY_FILENAME),
            false,
        ),
        _ => {
            return Err("rpc.tls_cert_path and rpc.tls_key_path must be set together".into());
        }
    };

    let source = if cert_path.exists() && key_path.exists() {
        if user_provided {
            CertSource::UserProvided
        } else {
            CertSource::AutoLoaded
        }
    } else if user_provided {
        return Err(format!(
            "configured TLS cert ({}) or key ({}) does not exist",
            cert_path.display(),
            key_path.display(),
        ));
    } else {
        std::fs::create_dir_all(data_dir).map_err(|e| format!("create data dir: {e}"))?;
        let (cert_pem, key_pem) = generate_self_signed()?;
        std::fs::write(&cert_path, cert_pem)
            .map_err(|e| format!("write {}: {e}", cert_path.display()))?;
        std::fs::write(&key_path, key_pem)
            .map_err(|e| format!("write {}: {e}", key_path.display()))?;
        restrict_to_owner(&key_path);
        CertSource::AutoGenerated
    };

    let config = build_rustls_config(&cert_path, &key_path)?;
    Ok((config, source, cert_path))
}

/// Build a `rustls::ServerConfig` from PEM files on disk.
fn build_rustls_config(cert_path: &Path, key_path: &Path) -> Result<Arc<ServerConfig>, String> {
    let cert_pem =
        std::fs::read(cert_path).map_err(|e| format!("read {}: {e}", cert_path.display()))?;
    let key_pem =
        std::fs::read(key_path).map_err(|e| format!("read {}: {e}", key_path.display()))?;

    let certs: Vec<CertificateDer<'static>> = rustls_pemfile::certs(&mut Cursor::new(&cert_pem))
        .collect::<Result<_, _>>()
        .map_err(|e| format!("parse {}: {e}", cert_path.display()))?;
    if certs.is_empty() {
        return Err(format!("no certificates in {}", cert_path.display()));
    }

    let key = load_private_key(&key_pem, key_path)?;

    ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(certs, key)
        .map(Arc::new)
        .map_err(|e| format!("rustls: {e}"))
}

/// Accept PKCS#8, RSA, or SEC1 PEM blocks — whichever the user
/// supplied.  `rcgen`-generated keys are PKCS#8, but a CA-signed
/// key could be any of the three.
fn load_private_key(pem: &[u8], path: &Path) -> Result<PrivateKeyDer<'static>, String> {
    let mut cursor = Cursor::new(pem);
    if let Some(k) = rustls_pemfile::private_key(&mut cursor)
        .map_err(|e| format!("parse {}: {e}", path.display()))?
    {
        return Ok(k);
    }
    Err(format!("no private key found in {}", path.display()))
}

/// Generate a fresh self-signed ECDSA P-256 cert valid for 10 years.
/// Returns `(cert_pem, key_pkcs8_pem)`.
fn generate_self_signed() -> Result<(String, String), String> {
    let mut params = CertificateParams::new(vec!["localhost".to_string()])
        .map_err(|e| format!("cert params: {e}"))?;
    let mut dn = DistinguishedName::new();
    dn.push(DnType::CommonName, "BitAiir RPC");
    params.distinguished_name = dn;

    // Accept connections to "localhost" and the two loopback IPs —
    // that's what `bitaiir-cli` and curl on the same host will use.
    params.subject_alt_names = vec![
        SanType::DnsName("localhost".try_into().map_err(|e| format!("SAN: {e}"))?),
        SanType::IpAddress(IpAddr::from([127u8, 0, 0, 1])),
        SanType::IpAddress(IpAddr::from([0u16, 0, 0, 0, 0, 0, 0, 1])),
    ];

    let (y, mo, d) = today_ymd();
    params.not_before = rcgen::date_time_ymd(y, mo, d);
    params.not_after = rcgen::date_time_ymd(y + SELF_SIGNED_VALIDITY_YEARS, mo, d);

    let key_pair = KeyPair::generate().map_err(|e| format!("keygen: {e}"))?;
    let cert = params
        .self_signed(&key_pair)
        .map_err(|e| format!("self-sign: {e}"))?;
    Ok((cert.pem(), key_pair.serialize_pem()))
}

/// Today's UTC date as `(year, month, day)`.  Kept inline so the
/// module has no dep on the `time` crate directly — `rcgen` pulls
/// it in transitively for `date_time_ymd`.
fn today_ymd() -> (i32, u8, u8) {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let mut days = secs / 86400;
    let mut y: i32 = 1970;
    loop {
        let dy = if is_leap(y) { 366 } else { 365 };
        if days < dy {
            break;
        }
        days -= dy;
        y += 1;
    }
    let leap = is_leap(y);
    let mdays = [
        31,
        if leap { 29 } else { 28 },
        31,
        30,
        31,
        30,
        31,
        31,
        30,
        31,
        30,
        31,
    ];
    let mut mo: u8 = 1;
    for (i, &md) in mdays.iter().enumerate() {
        if days < md {
            mo = (i + 1) as u8;
            break;
        }
        days -= md;
    }
    (y, mo, (days + 1) as u8)
}

fn is_leap(y: i32) -> bool {
    (y % 4 == 0 && y % 100 != 0) || y % 400 == 0
}

/// Best-effort `chmod 600` on the private key.  Silently ignored on
/// platforms without Unix permissions (Windows relies on ACLs we
/// don't touch — the file inherits the data dir's ACL).
#[cfg(unix)]
fn restrict_to_owner(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    if let Ok(meta) = std::fs::metadata(path) {
        let mut perms = meta.permissions();
        perms.set_mode(0o600);
        let _ = std::fs::set_permissions(path, perms);
    }
}

#[cfg(not(unix))]
fn restrict_to_owner(_path: &Path) {}
